name: swim-web-view
region: nyc
static_sites:
  - name: swimrnmobile
    github:
      branch: main
      deploy_on_push: true
    build_command: npm run vercel-build
    output_dir: dist
    catchall_document: index.html
    error_document: index.html
    routes:
      - path: /
    envs:
      - key: EXPO_PUBLIC_SUPABASE_URL
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: EXPO_PUBLIC_SUPABASE_ANON_KEY
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: EXPO_PUBLIC_APP_URL
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: EXPO_PUBLIC_WEB_SECRET_KEY
        scope: RUN_AND_BUILD_TIME
        type: SECRET
